# Generated by Django 5.2.5 on 2025-09-01 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('time', models.PositiveIntegerField(help_text='Round duration in seconds')),
                ('intensity', models.PositiveIntegerField(help_text='Intensity level from 1 to 10')),
                ('notes', models.TextField(blank=True, null=True)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='workouts.workout')),
            ],
        ),
    ]
