# Generated by Django 5.2.5 on 2025-09-01 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_type', models.CharField(choices=[('shadowboxing', 'Shadowboxing'), ('bagwork', 'Bag work'), ('pad_work', 'Pad Work'), ('sparring', 'Sparring'), ('conditioning', 'Conditioning'), ('strength_training', 'Strength Training'), ('flexibility', 'Flexibility'), ('jump_rope', 'Jump Rope'), ('heavy_bag', 'Heavy Bag'), ('calisthenics', 'Calisthenics'), ('abdominal', 'Abdominal'), ('footwork', 'Footwork'), ('running', 'Running'), ('other', 'Other')], max_length=50)),
                ('date', models.DateField()),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
